### ISSUE TITLE
Link is failing 

### ISSUE THREAD

**Issue by pratius** [leantechnologies/link-sdk-react-native#21]
Hi, 

This SDK is always throwing error connections. I have done the below configuration. Please let me know the missing configuration?

  <TouchableOpacity
        style={styles.cta_container}
        onPress={() =>
          Lean.current.link({
            app_token: "myToken",
            permissions: ["identity", "accounts", "balance", "transactions"],
            customer_id: "myCustID",
            sandbox: true,
          })
        }
![Simulator Screen Shot - iPhone 11 Pro Max - 2022-01-22 at 15 52 56](https://user-images.githubusercontent.com/15229476/150637571-01a88128-aced-4c73-b33a-f39d7bd01ea9.png)

**Comment by a-tomlinson** [comment]
@pratius it looks like you're passing in your appToken incorrectly in the sample shared above:

```
<TouchableOpacity
  style={styles.cta_container}
  onPress={() =>
    Lean.current.link({
      app_token: "myToken",
      permissions: ["identity", "accounts", "balance", "transactions"],
      customer_id: "myCustID",
      sandbox: true,
    })
}
```

assuming you have `myToken` as a stored variable, you should remove the `"` marks on either side so it's:

```
app_token: myToken
```

Same applies to the customer id
