### ISSUE TITLE
Lean WebView content custom styles

### ISSUE THREAD

**Issue by gpawlik** [leantechnologies/link-sdk-react-native#25]
Hello, is there a way to pass any custom styles to the lean WebView? I am struggling with the content being misaligned (look at the button position in the screenshot). I have tried to align it with many different configurations (inside SafeAreaView, outside of it, forcing the parent wrapper to have bottom padding, etc.) but I didn't find a solution so passing down the custom styles could be useful.

![lean-content](https://user-images.githubusercontent.com/6296883/169654737-f4e01af7-e671-47ad-9707-87bb54374e3a.png)

**Comment by a-tomlinson** [comment]
Hi @gpawlik - we now have full support for the Customization styles from our documentation here: https://docs.leantech.me/guides/customization/

This means you can configure the SDK far more than before - the team would love your feedback if there are additional parameters you would like to change!
