### ISSUE TITLE
Lean WebView crashing on Android 

### ISSUE THREAD

**Issue by othman95** [leantechnologies/link-sdk-react-native#45]
Hello, I'm using the react native SDK latest version and it's crashing on Android whenever I enter the lean screen then navigate back.
I'm using:
react-native: 0.70.6
lean-react-native: 0.16.0
react-native-screens: 3.20.0

I did a bit of research and the issue can be fixed by:
1- Adding androidLayerType : 'software' on the WebView, but then it will render using Android's software rendering pipeline which is much slower than hardware acceleration.
2- Removing the react native screen animation on the screen that has Lean, by adding animation: 'none' in the Stack.Screen component options.
The best solution to avoid the top 2 is a small rewrite of the index.js of lean SDK, I submitted a pull request, it solves the problem without the downsides of the top 2 points.
The pull request link is[ here ](https://github.com/leantechnologies/link-sdk-react-native/pull/44)

**Comment by dima-bezugly** [comment]
Hello @othman95,
Thank you for reporting this issue and researching the solution!

I wanted to merge it, but it conflicts with our latest updates, so we fixed it in #52. 

Please feel free to update the package to the `1.9.0` version.

Thanks!
